TENSORBOARD_LOG_DIRECTORY = './log/tensorboard/'
BATCH_SIZE = 32
LEARNING_RATE = 1e-3
LATENT_DIMS = 50
EPOCHS = 15
GENERATOR_WEIGHTS = {
    'distortion': 2000.,
    'discriminator': 100
}
CHANNELS=3
SSIM_SIGMA = 1.5
LOSS_WEIGHT = 1.
ALPHA = 0.75
